import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header/page";
import Footer from "./Footer/page";
import MobileHeader from "./MobileHeader/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="hidden lg:block">
        <Header/>
        </div>

        <div className="lg:hidden">
        <MobileHeader/>
        </div>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
